site_name: TI Portfolio
site_description: HBO-ICT Technische Informatica Portfolio
site_author: HBO-ICT
copyright: Copyright 2023 Hogeschool van Amsterdam

theme:
    name: material
    custom_dir: mdocotion/
    logo: assets/projectLogoSmall.png
    sidebar_color: 'rgb(250, 240, 230)'
    favicon: assets/robot.svg
    features:
        - navigation.sections
        - content.tabs.link

plugins:
    - search
    - mermaid2
    - awesome-pages
    - mkdocs-video:
        video_autoplay: False
        css_style:
          is_video: True
          min-width: "640px"
          max-width: "900px"
          min-height: "360px"     
    - section-index
    - autolinks
    - macros:
          modules: [mkdocs_macros_mdocotion]

markdown_extensions:
    - attr_list
    - admonition
    - md_in_html
    - fenced_code
    - pymdownx.highlight:
          linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
        permalink: true
    - pymdownx.details
